#!/bin/bash

while true;

do

echo "Updating and Starting Server"

    if siriproxy update; then

       echo "[Info - SiriProxy] Updating Complete!"
       siriproxy server;
       echo "[Info - SiriProxy] Restarter Bye"
 
      exit 1

    else

      echo "[Warning - Crash - SiriProxy] Crashed! Updating then restarting in 2 sec!"

      sleep 1

    fi



done
