#!/bin/bash

while true;

do

echo "Starting Server"

    if siriproxy server; then

       echo "[Info - Restarter] Bye"
 
      exit 1

    else

      echo "[Warning - Crash - SiriProxy] Crashed! Restarting in 2 sec!"

      sleep 1

    fi



done
