#!/bin/bash
while true;
do
echo "[Info - SiriProxy] Starting Server"
    if siriproxy server; then
       echo "[Info - SiriProxy] Restarter Bye"
      exit 1
    else
      echo "[Warning - Crash - SiriProxy] Crashed! Updating then restarting in 2 sec!"
      sleep 1
    fi
done
